<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <base href="/" />    
  </head>
  <body>
  <style type="text/css">
  body {
  margin: 0; 
  padding: 0; 
  font-family: 'Verdana', sans-serif;
  color: black;
}

body a {
  text-decoration: none;
  font-weight: bolder;
  color: #2441F5;
}

body a:hover {
  text-decoration: underline;
}

#header {
  height: 100px;
  background: #2441F5;
}

#logo {
  float: left;
  padding-left: 50px;
  padding-top: 10px;  
}


#content {
  min-height: 400px;  
  padding-left: 50px;
  padding-right: 50px;
}

#footer {
  float: right;
  font-size: smaller;
  background: #2441F5;
  padding-left: 20px;
  color: white;
}

#footer a {
  color: white;
}
  </style>
    <div id="header">
      <div id="logo">
        <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/images/logo.png" />
      </div>      
      <div id="menu">
      </div>
    </div>
    
    <div id="content">
      <?php echo $this->layout()->content ?>
    </div>
    
    <div id="footer">
      <p>Pilot Project, by Edgar Borges.</p>
    </div>    
  </body>
</html>